version: "3"
services:
  mongo_db:
    container_name: mongo_service
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #    MONGO_INITDB_ROOT_USERNAME: ash 
    #    MONGO_INITDB_ROOT_PASSWORD: 123  
    #    MONGO_INITDB_DATABASE: db
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    container_name: backend
    restart: always
    image: bsankapal/pennypilot-backend
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      MONGODB: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      # - ./frontend/build:/pennypilot/frontend/build
    networks:
      - finance
  frontend:
    build:
      dockerfile: dockerfile
      context: ./frontend/
    container_name: frontend
    restart: always
    image: bsankapal/pennypilot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - finance
    depends_on:
      - backend
networks:
  finance:
    driver: bridge
